### ISSUE TITLE
Project Document

### ISSUE THREAD

**Issue by jleei** [xuleiboy1234/autoTitle#1]
Hi, 
I am interested this project, are there project documents?

**Comment by xuleiboy1234** [comment]
@cdrlee Hi, this project is just a testing project, it reference OpenNMT(https://github.com/opennmt/opennmt), Sockeye(AWS https://github.com/awslabs/sockeye), Tensorflow(https://github.com/tensorflow/models/tree/master/research/textsum) tools, you can search and read some documents about these tools.Thanks.
